### ISSUE TITLE
文字直排與翻頁方向的判斷依據

### ISSUE THREAD

**Issue by WillyYeh** [dpublishing/epub3guide#10]
> 包裝文件（Package Document/OPF檔案）
>
> 遵守翻頁方向
>
> 書的翻頁方向必需依從包裝文件中Spine元素的page-progresson-direction屬性，不管內容文件或者樣式表中使用哪一種writing-mode。
>
> 而XHTML內容文件中的文字排列方向，則依照各XHTML中Body元素所指定的writing-mode屬性。當writing-mode指定於html元素時，必需繼承於body元素。
>
> 例如page-progression-direction指定為rtl（由右向左）時，而xhtml的writing-mode指定為horizontal-tb（橫排）時，期待文字於螢幕內「由左向右」顯示，而新的頁面則是「由右向左」增加。

這是文件中對於翻頁方向的規範，
我們團隊剛巧討論翻頁方向與文字走向的判斷依據，
翻到 Readium 對於這問題較完善的討論：[Readium-CSS](https://github.com/readium/readium-css/wiki/Internationalization,-pagination-and-user-settings)
Readium 的判斷依據：
1. 先判斷 OPF/metadata/dc:language 的值（包含第一與第二語言）
1. 然後是看 OPF/spine/@page-progression-direction 的值
1. 其他判斷依據還有 HTML 的 xml:lang 宣告
1. 最終文字走向仍得依據 CSS 的 dir 與 writing-mode 的值

由於不是所有 EPUB 都會正確地設定 OPF/spine/@page-progression-direction，
因此 RS 的判斷流程還請多加注意。

**Comment by bobbytung** [comment]
``page-progresson-direction`` 在本指南中為「必需」。
