### ISSUE TITLE
透明背景 png 用於缺字、表格、公式的考量

### ISSUE THREAD

**Issue by WillyYeh** [dpublishing/epub3guide#11]
最近與公司內部編輯團隊溝通此份文件，
對於透明背景 png 提出意見與各先進討論：
> 由於各家閱讀程式因應讀者需求，多半提供接近夜間模式（黑底白字）的閱讀模式，這時若 png 圖檔是黑色內容、透明背景，則會難以閱讀，敝公司是會刻意避開透明背景 PNG 圖（直接白底黑字 JPEG）。

**Comment by bobbytung** [comment]
同 #14 Rakuten Kobo Jeff的意見如下：

> "透明的PNG圖片" was mentioned but I personally don't suggest to use PNG with transparent background. The reason is many RS has theme feature (such as night mode) and when user switch to night mode it could make PNG image seems disappear. Image is not like text that UA would invert front color automatically.

所以這邊將「透明背景」改成「背景色為白色」，各位意見如何？
