### ISSUE TITLE
英文 's 的注意事項

### ISSUE THREAD

**Issue by WillyYeh** [dpublishing/epub3guide#13]
關於 's 在英文中用於所有格或縮寫時，
有時後會看到使用 "`s" 而非 "'s"。
這樣的內容在顯示時會讓名詞與所有格間有巨大的空白，
如：John’ s
建議 ’ s 應該避免使用，
而應該採用 's。

**Comment by bobbytung** [comment]
可直接在標點列表中加入推薦使用的Unicode代碼，煩請 @WillyYeh 提供建議。

**Comment by bobbytung** [comment]
@WillyYeh 還有沒有其他推薦的使用的英文標點？

**Comment by WillyYeh** [comment]
我剛剛有再與編輯同仁確認，
我們除了上述字元會特定以人工置換外，
其他就盡量不修改。
