### ISSUE TITLE
兩個以上OPF的敘述

### ISSUE THREAD

**Issue by bobbytung** [dpublishing/epub3guide#14]
根據Rakuten Kobo Jeff Xu提供的意見：

> #### <u>META-INF中的container.xml</u>
> 
> 本文件不提供具有兩個以上OPF檔案的範例，若有兩個以上OPF檔案時，請依照EPUB 3規範適當處理。

這一段來自日本電書協的描述過舊，實際上目前RS幾乎沒有做多重OPF檔案的支援，而一般流通的EPUB 3檔案也不會加入二個以上的OPF檔案。也就是說：EPUB 3規範有，但實際不通用。

建議隨著現狀刪除這一段落，各位意見如何？

**Comment by WillyYeh** [comment]
去年會議時有當面提及 Multiple Rendition，
得知是的確沒有後續發展。

**Comment by WillyYeh** [comment]
贊成移除。

**Comment by ccyanni** [comment]
刪除+1
