### ISSUE TITLE
流式書檔書封與章名頁

### ISSUE THREAD

**Issue by WillyYeh** [dpublishing/epub3guide#16]
Guideline 針對書封與章名頁已有相關章節說明，
我們在此提出一個額外增加的建議：
如果流式書檔中的書封與章名頁內容是單一圖檔，
建議將該頁做成獨立的版式 xhtml。
最近在 BOOKWALKER 提供的輕小說 EPUB 書檔中有許多使用這種製作方式，
呈現的效果是很好的，
不知道各位的想法如何？

**Comment by bobbytung** [comment]
BookWalker的意見是希望加入作為Reflow中單一圖片頁的標準做法，要是沒有意見，我就改寫規格加入了。

**Comment by dpublishing** [comment]
> 就目前狀況來說，BookWalker的輕小說已經在各平台上架銷售，應該都能支援這樣的作法。
> 所以問題是：這是一個選擇性（Optional）的作法，還是標準的推薦作法？

在呈現效果不錯，且多數平台均可支援（待查證）的情況下。我傾向作為建議的做法，這樣可以有一個統一的參照依據。所以我建議可以先納入規格，如果有其他不同的意見可再討論是否改為 optional。

**Comment by ccyanni** [comment]
> Book Walker的做法是將單一圖片的頁面，如圖片書名、章名、章節間或之前的單頁插畫以FXL SVG Wrapping的方式製作。需在Reflow OPF的`<package>`加入`prefix="rendition: http://www.idpf.org/vocab/rendition/#`
> 
> 然後在`<manifest>`中各單頁圖片頁面加入`properties="svg"`
> 
> 最後於`<spine>`也要加入`properties="rendition:layout-pre-paginated rendition:spread-auto page-spread-x"`
> 
> 就目前狀況來說，BookWalker的輕小說已經在各平台上架銷售，應該都能支援這樣的作法。
> 所以問題是：這是一個選擇性（Optional）的作法，還是標準的推薦作法？
> BookWalker的意見是希望加入作為Reflow中單一圖片頁的標準做法，要是沒有意見，我就改寫規格加入了。

在呈現效果不錯，且多數平台均可支援（待查證）的情況下。我傾向作為建議的做法，這樣可以有一個統一的參照依據。所以我建議可以先納入規格，如果有其他不同的意見可再討論是否改為 optional。
