### ISSUE TITLE
撰寫與EBPAJ的差異點

### ISSUE THREAD

**Issue by bobbytung** [dpublishing/epub3guide#23]

**Comment by dpublishing** [comment]
已新增初版內容至 Wiki： https://github.com/dpublishing/epub3guide/wiki/%E8%88%87EBPAJ-EPUB-3-Authoring-Guide%E7%9A%84%E5%B7%AE%E7%95%B0%EF%BC%88%E8%8D%89%E7%A8%BF%EF%BC%89
