### ISSUE TITLE
將 /samples/台灣EPUB 3製作指引.epub 改放在 / 底下

### ISSUE THREAD

**Issue by bobchao** [dpublishing/epub3guide#25]
目前放在 /samples/ 底下相對沒有那麼明顯，且以此檔案的內容屬性來說應該是與 tdpf-epub3guide.md 在同個層級，或許可以考慮改位置

**Comment by ccyanni** [comment]
就屬性上來，的確是比較適合放在 `/` 。另一個 issue 是目前的 EPUB 檔是手工做的，其實後來也有考慮是不是要用 Gitbook 直接吃 md 檔來產生 EPUB，這樣可以跟著 md 主檔的變更直接連動產生。

**Comment by dpublishing** [comment]
配合本次新增實作案例同步調整，將「台灣EPUB 3製作指引.epub」改為為封裝內容，並將目錄更名為「tdpf-epub3guide」同時提取到 `/` 根目錄。Commit: f5db590bcd82e418f3dd897abf9265da8630e42c
