### ISSUE TITLE
中文與其他語言缺字的處理建議

### ISSUE THREAD

**Issue by bobbytung** [dpublishing/epub3guide#3]
草稿內對於缺字的處理如下：

> ## 缺字圖片
> 
> 備註：
> 
> * Unicode Ext-B之後不在HKSCS內的漢字，一律以圖片顯示
> 
> * 要以哪款字型製作圖片，依照出版社指示
> 
> * 背景為透明，請以8bit PNG格式保存

日本電子書RS多半會搭配明體與黑體兩套字體，而字體會包含JIS 4161-1993所含字符。

繁體中文目前沒有像JIS 4161-1993那樣的字碼標準，若使用BIG 5碼標準則會有多種缺字狀況發生（如王建「煊」、游錫「堃」）。一般印刷用內文字體則是通常包含Unicode 3.0中的中日韓統一表意文字20,902字，以及HKSCS香港增補字符集5,033字。

Ext-B後的生罕用字雖然有部分會回退（Fallback）到系統字體，但系統字體不一定包含所有文字，所以建議比照日文處理JIS 4161-1993外字符（外字處理），製作成圖片插入內文，加上CSS來顯示。

但以上處理僅限於處理漢字缺字，當遇到泰文、越南文等文字時，需要討論該如何處理，

一般來說在macOS與iOS上會回退到其他語文的系統字體，但在Windows及Android上則常顯示為缺字。

推薦方式有二：

## 一、同樣將文字處理成圖片插入內文 

這種處理方式遇到較長的單詞或語句時會造成斷行問題。

## 二、以文字插入，加上lang標籤，再嵌入該語種的開放字體來處理。

日本電書協指南中不建議嵌入字體，但目前各瀏覽器與RS對於嵌入字體的支援相對完善。加上Google提供開放授權各語種的Noto字體可以使用，各語種字體的檔案尺寸也相對中文要小，大約數百KB到數MB而已。

若使用這種處理方式，需要各位測試自己RS的支援狀況。

**Comment by Huichun-Hu** [comment]
在編輯epub時如遇到難字，都會先上"中國哲學書電子書計劃字典"找字，用法如查字典。比較不建議造字。
https://ctext.org/dictionary.pl?if=gb
