### ISSUE TITLE
閱讀程式需支援與內容不得使用的HTML元素與CSS屬性

### ISSUE THREAD

**Issue by bobbytung** [dpublishing/epub3guide#4]
在草稿中有兩段落：
- RS需支援的HTML元素以及CSS屬性
- RS不需支援的HTML元素與CSS屬性

請各位檢視，並且判斷是否需要增減，如：

- 不需支援但廣泛應用在既有電子書的元素與屬性
- 少用、且與自己RS相容性有關希望不支援的元素與屬性。

**Comment by hwenchuang** [comment]
@bobbytung 博客來確認<code>和<pre>可以支援。

**Comment by bobbytung** [comment]
@hwenchuang 謝謝，因為製作的範本會使用到這兩個元素
