### ISSUE TITLE
identifier 的格式

### ISSUE THREAD

**Issue by WillyYeh** [dpublishing/epub3guide#7]
看到文件中對於 identifier 的格式規範如下：
> 檔案id（unique-identifier）原則上使用urn:isbn:xxxxxxxxxxxx，ISBN間不加連字號。沒有ISBN時，輸入UUID。

問了一下 Yanni 後，看來應該參考 [EPUB Identifier Schemes Registry](http://idpf.github.io/epub-registries/identifiers/#sec-types) 的寫法會比較合適。重點不在 urn:isbn: 的前置碼，而是使用 opf:scheme attribute 來定義。
> **ISBN**
> An International Standard Book Number.
> ```
> <dc:identifier opf:scheme="isbn">9780000000001</dc:identifier>
> <dc:identifier opf:scheme="isbn">urn:isbn:9780000000001</dc:identifier>
> ```

**Comment by bobbytung** [comment]
根據EPUB 3.3的[範例21：指定識別碼類型](https://dpublishing.github.io/epub-specs-tc/epub33_2023/EPUB_update/EPUB33.html#example-specifying-the-type-of-the-identifier)

建議使用`<meta>`標籤配合以下結構指定為ISBN13

```
<meta
       refines="#pub-id"
       property="identifier-type"
       scheme="onix:codelist15">
   </meta>
```
